In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("Preprocessing Dataset.csv")
df

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    10 non-null     str
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     str
dtypes: float64(2), str(2)
memory usage: 537.0 bytes

In [5]:
df["Country"].mode()

0    France
Name: Country, dtype: str

In [6]:
country_mode = df["Country"].mode()[0]

df["Country"] = df["Country"].fillna(country_mode)

df

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [7]:
age_median = df["Age"].median()

df["Age"] = df["Age"].fillna(age_median)

df

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain  38.0  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [8]:
salary_mean = round(df["Salary"].mean())

df["Salary"] = df["Salary"].fillna(salary_mean)

df

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0  63778.0       Yes
5   France  35.0  58000.0       Yes
6    Spain  38.0  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [9]:
df.isnull().sum()

Country      0
Age          0
Salary       0
Purchased    0
dtype: int64

In [10]:
country_dummies = pd.get_dummies(df["Country"])

country_dummies

   France  Germany  Spain
0    True    False  False
1   False    False   True
2   False     True  False
3   False    False   True
4   False     True  False
5    True    False  False
6   False    False   True
7    True    False  False
8   False     True  False
9    True    False  False

In [11]:
updated_dataset = pd.concat(
    [country_dummies, df[["Age", "Salary", "Purchased"]]],
    axis=1
)

updated_dataset

   France  Germany  Spain   Age   Salary Purchased
0    True    False  False  44.0  72000.0        No
1   False    False   True  27.0  48000.0       Yes
2   False     True  False  30.0  54000.0        No
3   False    False   True  38.0  61000.0        No
4   False     True  False  40.0  63778.0       Yes
5    True    False  False  35.0  58000.0       Yes
6   False    False   True  38.0  52000.0        No
7    True    False  False  48.0  79000.0       Yes
8   False     True  False  50.0  83000.0        No
9    True    False  False  37.0  67000.0       Yes

In [12]:
updated_dataset["Purchased"] = updated_dataset["Purchased"].replace({
    "No": 0,
    "Yes": 1
})

updated_dataset

   France  Germany  Spain   Age   Salary Purchased
0    True    False  False  44.0  72000.0         0
1   False    False   True  27.0  48000.0         1
2   False     True  False  30.0  54000.0         0
3   False    False   True  38.0  61000.0         0
4   False     True  False  40.0  63778.0         1
5    True    False  False  35.0  58000.0         1
6   False    False   True  38.0  52000.0         0
7    True    False  False  48.0  79000.0         1
8   False     True  False  50.0  83000.0         0
9    True    False  False  37.0  67000.0         1

In [13]:
updated_dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   France     10 non-null     bool
 1   Germany    10 non-null     bool
 2   Spain      10 non-null     bool
 3   Age        10 non-null     float64
 4   Salary     10 non-null     float64
 5   Purchased  10 non-null     object
dtypes: bool(3), float64(2), object(1)
memory usage: 402.0+ bytes